server:
  port: 8080
  servlet:
    context-path: /v1/

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/click-service-project
    password: PIh4Yrv75BLP1SuXY9XU
    driver-class-name: org.postgresql.Driver
    username: click-service-project
  flyway:
    url: jdbc:postgresql://localhost:5432/click-service-project
    user: click-service-project
    password: PIh4Yrv75BLP1SuXY9XU
    driver-class-name: org.postgresql.Driver
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    web: DEBUG
